### ISSUE TITLE
Week02作业

### ISSUE THREAD

**Issue by liyuan932** [algorithm022/algorithm022#4]
#学号:G20200343190126
#语言: Java
#作业链接: https://github.com/liyuan932/algorithm022/tree/main/Week_02

**Comment by hifish78** [comment]
#学号:G20200389060102
#语言: Python3
#作业链接: https://github.com/hifish78/algorithm022/tree/main/Week_02

**Comment by Janway-WIn** [comment]
#学号:G20200343190074
#语言: CPP
#作业链接: https://github.com/Janway-WIn/algorithm022/tree/main/Week_02
